version: '3.1'
services:
  db:
    image: influxdb:1.8.1
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: SFXCPYi0acgAIVBF
      INFLUXDB_USER: influxdb
      INFLUXDB_USER_PASSWORD: wIx87kbD9hycJyrG
    ports:
      - 8086:8086
    volumes:
      - /Users/fenglex/data/influxdb:/var/lib/influxdb